# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main, filter-files ]
  pull_request:
    branches: [ main, filter-files ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: creates the wanted files in output_temp/ - example script
        run:  sh ./build.sh
      - name: filters output_temp/ to output/ using rsync (to exclude *.epub in this example)
        run:  rsync -arv --exclude="*.epub" output_temp/ output/
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output/
          destination-github-username: 'cpina'
          destination-repository-name: 'push-to-another-repository-output'
          user-email: carles3@pina.cat
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
